use_frameworks!

platform :ios, '9.0'

target 'PluginApplication_Example' do
  pod 'PluginApplication', :path => '../'

  target 'PluginApplication_Tests' do
    inherit! :search_paths

    
  end
end
